[book]
authors = ["Tavian Barnes"]
title = "tavianator.com"

[rust]
edition = "2021"

[build]
build-dir = "site"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/tavianator/tavianator.com"

[output.html.playground]
copyable = false

[output.html.print]
enable = false
